# Generated by Django 3.2.6 on 2022-05-13 07:56

import collections
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prodocore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='codename',
            field=models.SlugField(blank=True, max_length=255, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='group',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='properties',
            field=jsonfield.fields.JSONField(blank=True, default={}, load_kwargs={'object_pairs_hook': collections.OrderedDict}, verbose_name='properties'),
        ),
        migrations.AlterField(
            model_name='groupentity',
            name='codename',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='groupentity',
            name='label',
            field=models.CharField(max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='groupmemberrole',
            name='codename',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='groupmemberrole',
            name='label',
            field=models.CharField(max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='codename',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='label',
            field=models.CharField(max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='username'),
        ),
    ]
