# Generated by Django 3.2.6 on 2022-05-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('Time', ''), ('Table', ''), ('Text', ''), ('Check', ''), ('HTML', ''), ('Long Text', ''), ('Phone', ''), ('Data', ''), ('Rating', ''), ('Currency', ''), ('Attach Image', ''), ('Table MultiSelect', ''), ('Image', ''), ('Percent', ''), ('Dynamic Link', ''), ('Color', ''), ('Icon', ''), ('Float', ''), ('Code', ''), ('HTML Editor', ''), ('Attach', ''), ('Datetime', ''), ('Autocomplete', ''), ('Duration', ''), ('Fold', ''), ('Markdown Editor', ''), ('Password', ''), ('Select', ''), ('Text Editor', ''), ('Section Break', ''), ('Button', ''), ('Tab Break', ''), ('Column Break', ''), ('Small Text', ''), ('Read Only', ''), ('Link', ''), ('Date', ''), ('Heading', ''), ('Geolocation', ''), ('Signature', ''), ('JSON', ''), ('Barcode', ''), ('Int', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('2', ''), ('5', ''), ('8', ''), ('1', ''), ('7', ''), ('4', ''), ('6', ''), ('9', ''), ('3', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Document', 'Document'), ('System', 'System'), ('Other', 'Other'), ('Setup', 'Setup')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='engine',
            field=models.CharField(blank=True, choices=[('InnoDB', 'InnoDB'), ('MyISAM', 'MyISAM')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='sort_order',
            field=models.CharField(blank=True, choices=[('DESC', 'DESC'), ('ASC', 'ASC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('1', 'Blue'), ('10', 'Yellow'), ('2', 'Cyan'), ('3', 'Gray'), ('7', 'Pink'), ('8', 'Purple'), ('6', 'Orange'), ('9', 'Red'), ('4', 'Green'), ('5', 'Light Blue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('Document', 'Document'), ('Setup', 'Setup'), ('Other', 'Other'), ('System', 'System')], max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar_item',
            name='item_type',
            field=models.CharField(choices=[('Action', 'Action'), ('Separator', 'Separator'), ('Route', 'Route')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='license_type',
            field=models.CharField(choices=[('GNU Affero General', 'GNU Affero General'), ('Public License', 'Public License'), ('MIT License', 'MIT License'), ('GNU General Public License', 'GNU General Public License')], max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='standard',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Queued', 'Queued'), ('Error', 'Error')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_standard',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Script Report', 'Script Report'), ('Query Report', 'Query Report'), ('Report Builder', 'Report Builder'), ('Custom Report', 'Custom Report')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('Float', 'Float'), ('Date', 'Date'), ('ManyToOneRelation', 'ManyToOneRelation'), ('boolean', 'boolean'), ('charfield', 'charfield'), ('Currency', 'Currency'), ('DateField', 'DateField'), ('ManyToManyField', 'ManyToManyField'), ('OneToManyRelation', 'OneToManyRelation'), ('IntigerField', 'IntigerField'), ('ForeignKey', 'ForeignKey'), ('OneToOneRelation', 'OneToOneRelation')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_log',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Failed', 'Failed'), ('Complete', 'Complete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Monthly Long', 'Monthly Long'), ('Monthly', 'Monthly'), ('Cron', 'Cron'), ('Yearly', 'Yearly'), ('Daily', 'Daily'), ('Hourly Long', 'Hourly Long'), ('Weekly', 'Weekly'), ('Weekly Long', 'Weekly Long'), ('Daily Long', 'Daily Long'), ('Annual', 'Annual'), ('All', 'All')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('On Payment Authorization', 'On Payment Authorization'), ('Before Submit', 'Before Submit'), ('After Cancel', 'After Cancel'), ('Before Save', 'After Save'), ('After Submit', 'After Submit'), ('After Delete', 'After Delete'), ('Before Validate', 'Before Validate'), ('Before Save', 'Before Save'), ('After Save', 'After Save'), ('Before Delete', 'Before Delete'), ('After Insert', 'After Insert'), ('Before Insert', 'Before Insert'), ('Before Cancel', 'Before Cancel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Monthly Long', 'Monthly Long'), ('Monthly', 'Monthly'), ('Cron', 'Cron'), ('Yearly', 'Yearly'), ('Daily', 'Daily'), ('Hourly Long', 'Hourly Long'), ('Weekly', 'Weekly'), ('Weekly Long', 'Weekly Long'), ('Daily Long', 'Daily Long'), ('Annual', 'Annual'), ('All', 'All')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='script_type',
            field=models.CharField(choices=[('Scheduler Event', 'Scheduler Event'), ('API', 'API'), ('DocType Event', 'DocType Event'), ('Permission Query', 'Permission Query')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('2', ''), ('5', ''), ('8', ''), ('1', ''), ('7', ''), ('4', ''), ('6', ''), ('9', ''), ('0', ''), ('3', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('ymd', 'yyyy-mm-dd'), ('mdy', 'mm/dd/yyyy'), ('dmy', 'dd.mm.yyyy'), ('mdy', 'mm-dd-yyyy'), ('dmy', 'dd-mm-yyyy'), ('dmy', 'dd/mm/yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Sunday', 'Sunday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('2', ''), ('5', ''), ('8', ''), ('7', ''), ('4', ''), ('6', ''), ('9', ''), ('3', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='time_format',
            field=models.CharField(choices=[('24', 'HH:mm:ss'), ('12', 'HH:mm')], max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='contribution_status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('verified', 'verified')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='desk_theme',
            field=models.CharField(blank=True, choices=[('Dark', 'Dark'), ('Automatic', 'Automatic'), ('Light', 'Light')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Hourly', 'Hourly'), ('Weekly', 'Weekly'), ('Daily', 'Daily')], max_length=100, null=True),
        ),
    ]
