# Generated by Django 4.0.4 on 2022-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_import',
            name='Pending',
            field=models.CharField(blank=True, choices=[('Success', 'Success'), ('Error', 'Error'), ('Partial Success', 'Partial Success')], default='Success', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('Barcode', ''), ('HTML', ''), ('Code', ''), ('Phone', ''), ('Table MultiSelect', ''), ('Duration', ''), ('Heading', ''), ('Tab Break', ''), ('Int', ''), ('Section Break', ''), ('Percent', ''), ('Column Break', ''), ('Datetime', ''), ('Text Editor', ''), ('Markdown Editor', ''), ('Attach', ''), ('Small Text', ''), ('Attach Image', ''), ('Color', ''), ('Image', ''), ('JSON', ''), ('Float', ''), ('Select', ''), ('Password', ''), ('Currency', ''), ('Check', ''), ('Geolocation', ''), ('Signature', ''), ('Text', ''), ('Table', ''), ('HTML Editor', ''), ('Date', ''), ('Button', ''), ('Rating', ''), ('Dynamic Link', ''), ('Read Only', ''), ('Icon', ''), ('Data', ''), ('Fold', ''), ('Autocomplete', ''), ('Long Text', ''), ('Link', ''), ('Time', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('8', ''), ('2', ''), ('5', ''), ('3', ''), ('1', ''), ('9', ''), ('6', ''), ('4', ''), ('7', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Document', 'Document'), ('Setup', 'Setup'), ('System', 'System'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('4', 'Green'), ('9', 'Red'), ('1', 'Blue'), ('7', 'Pink'), ('5', 'Light Blue'), ('10', 'Yellow'), ('6', 'Orange'), ('2', 'Cyan'), ('3', 'Gray'), ('8', 'Purple')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('Document', 'Document'), ('Setup', 'Setup'), ('System', 'System'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar_item',
            name='item_type',
            field=models.CharField(choices=[('Action', 'Action'), ('Separator', 'Separator'), ('Route', 'Route')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='license_type',
            field=models.CharField(choices=[('MIT License', 'MIT License'), ('Public License', 'Public License'), ('GNU Affero General', 'GNU Affero General'), ('GNU General Public License', 'GNU General Public License')], max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='standard',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Error', 'Error'), ('Queued', 'Queued'), ('Completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_standard',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Query Report', 'Query Report'), ('Script Report', 'Script Report'), ('Report Builder', 'Report Builder'), ('Custom Report', 'Custom Report')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('ManyToManyField', 'ManyToManyField'), ('OneToOneRelation', 'OneToOneRelation'), ('ManyToOneRelation', 'ManyToOneRelation'), ('charfield', 'charfield'), ('Float', 'Float'), ('Currency', 'Currency'), ('IntigerField', 'IntigerField'), ('OneToManyRelation', 'OneToManyRelation'), ('Date', 'Date'), ('DateField', 'DateField'), ('ForeignKey', 'ForeignKey'), ('boolean', 'boolean')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_log',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Failed', 'Failed'), ('Complete', 'Complete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('All', 'All'), ('Weekly', 'Weekly'), ('Monthly Long', 'Monthly Long'), ('Yearly', 'Yearly'), ('Daily', 'Daily'), ('Cron', 'Cron'), ('Hourly', 'Hourly'), ('Hourly Long', 'Hourly Long'), ('Annual', 'Annual'), ('Daily Long', 'Daily Long'), ('Weekly Long', 'Weekly Long'), ('Monthly', 'Monthly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('Before Insert', 'Before Insert'), ('Before Save', 'Before Save'), ('Before Submit', 'Before Submit'), ('After Cancel', 'After Cancel'), ('Before Cancel', 'Before Cancel'), ('After Save', 'After Save'), ('Before Save', 'After Save'), ('After Submit', 'After Submit'), ('Before Validate', 'Before Validate'), ('After Delete', 'After Delete'), ('On Payment Authorization', 'On Payment Authorization'), ('After Insert', 'After Insert'), ('Before Delete', 'Before Delete')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('All', 'All'), ('Weekly', 'Weekly'), ('Monthly Long', 'Monthly Long'), ('Yearly', 'Yearly'), ('Daily', 'Daily'), ('Cron', 'Cron'), ('Hourly', 'Hourly'), ('Hourly Long', 'Hourly Long'), ('Annual', 'Annual'), ('Daily Long', 'Daily Long'), ('Weekly Long', 'Weekly Long'), ('Monthly', 'Monthly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='script_type',
            field=models.CharField(choices=[('Scheduler Event', 'Scheduler Event'), ('Permission Query', 'Permission Query'), ('DocType Event', 'DocType Event'), ('API', 'API')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('8', ''), ('2', ''), ('5', ''), ('3', ''), ('1', ''), ('9', ''), ('0', ''), ('6', ''), ('4', ''), ('7', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('mdy', 'mm-dd-yyyy'), ('mdy', 'mm/dd/yyyy'), ('ymd', 'yyyy-mm-dd'), ('dmy', 'dd.mm.yyyy'), ('dmy', 'dd-mm-yyyy'), ('dmy', 'dd/mm/yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Thursday', 'Thursday'), ('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('8', ''), ('2', ''), ('5', ''), ('3', ''), ('9', ''), ('6', ''), ('4', ''), ('7', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('All', 'All'), ('Weekly', 'Weekly'), ('Hourly', 'Hourly')], max_length=100, null=True),
        ),
    ]
