# Generated by Django 3.2.6 on 2022-05-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220513_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_import',
            name='Pending',
            field=models.CharField(blank=True, choices=[('Success', 'Success'), ('Error', 'Error'), ('Partial Success', 'Partial Success')], default='Success', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('HTML Editor', ''), ('Text Editor', ''), ('Fold', ''), ('HTML', ''), ('Image', ''), ('Small Text', ''), ('Rating', ''), ('Link', ''), ('Long Text', ''), ('Color', ''), ('Read Only', ''), ('Column Break', ''), ('Table MultiSelect', ''), ('Section Break', ''), ('Heading', ''), ('Currency', ''), ('Attach Image', ''), ('Duration', ''), ('Icon', ''), ('Code', ''), ('Data', ''), ('Select', ''), ('Markdown Editor', ''), ('Date', ''), ('JSON', ''), ('Float', ''), ('Button', ''), ('Text', ''), ('Tab Break', ''), ('Geolocation', ''), ('Attach', ''), ('Phone', ''), ('Table', ''), ('Int', ''), ('Signature', ''), ('Check', ''), ('Dynamic Link', ''), ('Percent', ''), ('Autocomplete', ''), ('Password', ''), ('Datetime', ''), ('Barcode', ''), ('Time', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('6', ''), ('5', ''), ('1', ''), ('2', ''), ('3', ''), ('4', ''), ('7', ''), ('8', ''), ('9', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('System', 'System'), ('Setup', 'Setup'), ('Document', 'Document'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='sort_order',
            field=models.CharField(blank=True, choices=[('ASC', 'ASC'), ('DESC', 'DESC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('7', 'Pink'), ('2', 'Cyan'), ('5', 'Light Blue'), ('8', 'Purple'), ('10', 'Yellow'), ('6', 'Orange'), ('9', 'Red'), ('3', 'Gray'), ('1', 'Blue'), ('4', 'Green')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('System', 'System'), ('Setup', 'Setup'), ('Document', 'Document'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar_item',
            name='item_type',
            field=models.CharField(choices=[('Action', 'Action'), ('Route', 'Route'), ('Separator', 'Separator')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='license_type',
            field=models.CharField(choices=[('GNU Affero General', 'GNU Affero General'), ('MIT License', 'MIT License'), ('Public License', 'Public License'), ('GNU General Public License', 'GNU General Public License')], max_length=255),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Error', 'Error'), ('Queued', 'Queued')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Script Report', 'Script Report'), ('Custom Report', 'Custom Report'), ('Report Builder', 'Report Builder'), ('Query Report', 'Query Report')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('ForeignKey', 'ForeignKey'), ('boolean', 'boolean'), ('ManyToOneRelation', 'ManyToOneRelation'), ('charfield', 'charfield'), ('OneToOneRelation', 'OneToOneRelation'), ('Currency', 'Currency'), ('IntigerField', 'IntigerField'), ('Date', 'Date'), ('ManyToManyField', 'ManyToManyField'), ('DateField', 'DateField'), ('Float', 'Float'), ('OneToManyRelation', 'OneToManyRelation')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_log',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Scheduled', 'Scheduled'), ('Failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('Hourly Long', 'Hourly Long'), ('Weekly', 'Weekly'), ('Hourly', 'Hourly'), ('All', 'All'), ('Monthly Long', 'Monthly Long'), ('Annual', 'Annual'), ('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Weekly Long', 'Weekly Long'), ('Daily Long', 'Daily Long'), ('Yearly', 'Yearly'), ('Cron', 'Cron')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('After Insert', 'After Insert'), ('On Payment Authorization', 'On Payment Authorization'), ('After Delete', 'After Delete'), ('Before Submit', 'Before Submit'), ('Before Delete', 'Before Delete'), ('Before Insert', 'Before Insert'), ('Before Save', 'Before Save'), ('After Submit', 'After Submit'), ('After Save', 'After Save'), ('Before Cancel', 'Before Cancel'), ('Before Save', 'After Save'), ('Before Validate', 'Before Validate'), ('After Cancel', 'After Cancel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('Hourly Long', 'Hourly Long'), ('Weekly', 'Weekly'), ('Hourly', 'Hourly'), ('All', 'All'), ('Monthly Long', 'Monthly Long'), ('Annual', 'Annual'), ('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Weekly Long', 'Weekly Long'), ('Daily Long', 'Daily Long'), ('Yearly', 'Yearly'), ('Cron', 'Cron')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='script_type',
            field=models.CharField(choices=[('DocType Event', 'DocType Event'), ('Scheduler Event', 'Scheduler Event'), ('Permission Query', 'Permission Query'), ('API', 'API')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('6', ''), ('0', ''), ('5', ''), ('1', ''), ('2', ''), ('3', ''), ('4', ''), ('7', ''), ('8', ''), ('9', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('dmy', 'dd/mm/yyyy'), ('mdy', 'mm-dd-yyyy'), ('ymd', 'yyyy-mm-dd'), ('dmy', 'dd-mm-yyyy'), ('mdy', 'mm/dd/yyyy'), ('dmy', 'dd.mm.yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('6', ''), ('5', ''), ('2', ''), ('3', ''), ('4', ''), ('7', ''), ('8', ''), ('9', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='time_format',
            field=models.CharField(choices=[('12', 'HH:mm'), ('24', 'HH:mm:ss')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='desk_theme',
            field=models.CharField(blank=True, choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Automatic', 'Automatic')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('All', 'All'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=100, null=True),
        ),
    ]
