# Generated by Django 4.0.4 on 2022-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_data_import_pending_alter_docfield_fieldtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_import',
            name='Pending',
            field=models.CharField(blank=True, choices=[('Partial Success', 'Partial Success'), ('Error', 'Error'), ('Success', 'Success')], default='Success', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('Read Only', ''), ('Signature', ''), ('Button', ''), ('Code', ''), ('Image', ''), ('Table MultiSelect', ''), ('JSON', ''), ('Table', ''), ('HTML Editor', ''), ('Check', ''), ('Date', ''), ('HTML', ''), ('Rating', ''), ('Phone', ''), ('Select', ''), ('Attach Image', ''), ('Duration', ''), ('Dynamic Link', ''), ('Datetime', ''), ('Percent', ''), ('Icon', ''), ('Geolocation', ''), ('Long Text', ''), ('Float', ''), ('Text', ''), ('Text Editor', ''), ('Small Text', ''), ('Column Break', ''), ('Attach', ''), ('Currency', ''), ('Link', ''), ('Fold', ''), ('Barcode', ''), ('Section Break', ''), ('Tab Break', ''), ('Password', ''), ('Time', ''), ('Color', ''), ('Heading', ''), ('Data', ''), ('Markdown Editor', ''), ('Int', ''), ('Autocomplete', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('5', ''), ('3', ''), ('9', ''), ('4', ''), ('7', ''), ('8', ''), ('1', ''), ('6', ''), ('2', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Setup', 'Setup'), ('System', 'System'), ('Document', 'Document')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('6', 'Orange'), ('3', 'Gray'), ('9', 'Red'), ('1', 'Blue'), ('7', 'Pink'), ('8', 'Purple'), ('10', 'Yellow'), ('2', 'Cyan'), ('4', 'Green'), ('5', 'Light Blue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('Other', 'Other'), ('Setup', 'Setup'), ('System', 'System'), ('Document', 'Document')], max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar_item',
            name='item_type',
            field=models.CharField(choices=[('Route', 'Route'), ('Action', 'Action'), ('Separator', 'Separator')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='license_type',
            field=models.CharField(choices=[('Public License', 'Public License'), ('MIT License', 'MIT License'), ('GNU General Public License', 'GNU General Public License'), ('GNU Affero General', 'GNU Affero General')], max_length=255),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Queued', 'Queued'), ('Error', 'Error')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('Currency', 'Currency'), ('boolean', 'boolean'), ('OneToOneRelation', 'OneToOneRelation'), ('OneToManyRelation', 'OneToManyRelation'), ('charfield', 'charfield'), ('DateField', 'DateField'), ('Date', 'Date'), ('Float', 'Float'), ('ForeignKey', 'ForeignKey'), ('IntigerField', 'IntigerField'), ('ManyToManyField', 'ManyToManyField'), ('ManyToOneRelation', 'ManyToOneRelation')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_log',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Complete', 'Complete'), ('Failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('Monthly Long', 'Monthly Long'), ('Annual', 'Annual'), ('Weekly Long', 'Weekly Long'), ('All', 'All'), ('Daily', 'Daily'), ('Hourly Long', 'Hourly Long'), ('Yearly', 'Yearly'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Daily Long', 'Daily Long'), ('Cron', 'Cron'), ('Hourly', 'Hourly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('Before Cancel', 'Before Cancel'), ('After Delete', 'After Delete'), ('After Cancel', 'After Cancel'), ('After Save', 'After Save'), ('Before Validate', 'Before Validate'), ('Before Submit', 'Before Submit'), ('After Insert', 'After Insert'), ('Before Save', 'Before Save'), ('Before Insert', 'Before Insert'), ('Before Save', 'After Save'), ('Before Delete', 'Before Delete'), ('After Submit', 'After Submit'), ('On Payment Authorization', 'On Payment Authorization')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('Monthly Long', 'Monthly Long'), ('Annual', 'Annual'), ('Weekly Long', 'Weekly Long'), ('All', 'All'), ('Daily', 'Daily'), ('Hourly Long', 'Hourly Long'), ('Yearly', 'Yearly'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Daily Long', 'Daily Long'), ('Cron', 'Cron'), ('Hourly', 'Hourly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('5', ''), ('3', ''), ('9', ''), ('4', ''), ('8', ''), ('7', ''), ('1', ''), ('6', ''), ('2', ''), ('0', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('mdy', 'mm/dd/yyyy'), ('dmy', 'dd-mm-yyyy'), ('dmy', 'dd.mm.yyyy'), ('ymd', 'yyyy-mm-dd'), ('dmy', 'dd/mm/yyyy'), ('mdy', 'mm-dd-yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Monday', 'Monday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('5', ''), ('3', ''), ('9', ''), ('4', ''), ('8', ''), ('7', ''), ('6', ''), ('2', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='time_format',
            field=models.CharField(choices=[('12', 'HH:mm'), ('24', 'HH:mm:ss')], max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='contribution_status',
            field=models.CharField(choices=[('verified', 'verified'), ('rejected', 'rejected'), ('pending', 'pending')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='desk_theme',
            field=models.CharField(blank=True, choices=[('Dark', 'Dark'), ('Light', 'Light'), ('Automatic', 'Automatic')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('All', 'All'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=100, null=True),
        ),
    ]
