# Generated by Django 3.2.6 on 2022-05-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220513_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_import',
            name='Pending',
            field=models.CharField(blank=True, choices=[('Success', 'Success'), ('Partial Success', 'Partial Success'), ('Error', 'Error')], default='Success', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('Markdown Editor', ''), ('Small Text', ''), ('Geolocation', ''), ('Table MultiSelect', ''), ('Text Editor', ''), ('Color', ''), ('Data', ''), ('Icon', ''), ('Column Break', ''), ('Check', ''), ('Password', ''), ('Link', ''), ('Float', ''), ('Date', ''), ('Time', ''), ('Autocomplete', ''), ('HTML Editor', ''), ('Dynamic Link', ''), ('Attach Image', ''), ('Select', ''), ('Read Only', ''), ('Heading', ''), ('Fold', ''), ('Rating', ''), ('Phone', ''), ('Image', ''), ('Int', ''), ('Button', ''), ('Section Break', ''), ('Attach', ''), ('Signature', ''), ('Duration', ''), ('Long Text', ''), ('Percent', ''), ('Table', ''), ('Text', ''), ('Code', ''), ('Currency', ''), ('Tab Break', ''), ('Barcode', ''), ('JSON', ''), ('HTML', ''), ('Datetime', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('5', ''), ('1', ''), ('4', ''), ('8', ''), ('6', ''), ('9', ''), ('2', ''), ('7', ''), ('3', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Document', 'Document'), ('Other', 'Other'), ('System', 'System'), ('Setup', 'Setup')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='engine',
            field=models.CharField(blank=True, choices=[('MyISAM', 'MyISAM'), ('InnoDB', 'InnoDB')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='name_case',
            field=models.CharField(blank=True, choices=[('UPPER CASE', 'UPPER CASE'), ('Title Case', 'Title Case')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='sort_order',
            field=models.CharField(blank=True, choices=[('DESC', 'DESC'), ('ASC', 'ASC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('4', 'Green'), ('1', 'Blue'), ('9', 'Red'), ('2', 'Cyan'), ('10', 'Yellow'), ('5', 'Light Blue'), ('6', 'Orange'), ('8', 'Purple'), ('7', 'Pink'), ('3', 'Gray')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('Document', 'Document'), ('Other', 'Other'), ('System', 'System'), ('Setup', 'Setup')], max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar_item',
            name='item_type',
            field=models.CharField(choices=[('Action', 'Action'), ('Separator', 'Separator'), ('Route', 'Route')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='license_type',
            field=models.CharField(choices=[('Public License', 'Public License'), ('GNU General Public License', 'GNU General Public License'), ('GNU Affero General', 'GNU Affero General'), ('MIT License', 'MIT License')], max_length=255),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Error', 'Error'), ('Queued', 'Queued'), ('Completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Report Builder', 'Report Builder'), ('Script Report', 'Script Report'), ('Custom Report', 'Custom Report'), ('Query Report', 'Query Report')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('charfield', 'charfield'), ('ManyToManyField', 'ManyToManyField'), ('OneToManyRelation', 'OneToManyRelation'), ('Currency', 'Currency'), ('Float', 'Float'), ('boolean', 'boolean'), ('ManyToOneRelation', 'ManyToOneRelation'), ('ForeignKey', 'ForeignKey'), ('DateField', 'DateField'), ('IntigerField', 'IntigerField'), ('OneToOneRelation', 'OneToOneRelation'), ('Date', 'Date')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_log',
            name='status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Complete', 'Complete'), ('Scheduled', 'Scheduled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('All', 'All'), ('Hourly Long', 'Hourly Long'), ('Daily', 'Daily'), ('Hourly', 'Hourly'), ('Weekly', 'Weekly'), ('Cron', 'Cron'), ('Monthly Long', 'Monthly Long'), ('Yearly', 'Yearly'), ('Weekly Long', 'Weekly Long'), ('Monthly', 'Monthly'), ('Daily Long', 'Daily Long'), ('Annual', 'Annual')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('Before Insert', 'Before Insert'), ('After Insert', 'After Insert'), ('Before Validate', 'Before Validate'), ('Before Save', 'Before Save'), ('After Submit', 'After Submit'), ('Before Save', 'After Save'), ('After Delete', 'After Delete'), ('On Payment Authorization', 'On Payment Authorization'), ('Before Cancel', 'Before Cancel'), ('Before Delete', 'Before Delete'), ('After Cancel', 'After Cancel'), ('After Save', 'After Save'), ('Before Submit', 'Before Submit')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('All', 'All'), ('Hourly Long', 'Hourly Long'), ('Daily', 'Daily'), ('Hourly', 'Hourly'), ('Weekly', 'Weekly'), ('Cron', 'Cron'), ('Monthly Long', 'Monthly Long'), ('Yearly', 'Yearly'), ('Weekly Long', 'Weekly Long'), ('Monthly', 'Monthly'), ('Daily Long', 'Daily Long'), ('Annual', 'Annual')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='script_type',
            field=models.CharField(choices=[('Scheduler Event', 'Scheduler Event'), ('DocType Event', 'DocType Event'), ('Permission Query', 'Permission Query'), ('API', 'API')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('5', ''), ('1', ''), ('4', ''), ('8', ''), ('6', ''), ('9', ''), ('2', ''), ('0', ''), ('7', ''), ('3', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('dmy', 'dd.mm.yyyy'), ('mdy', 'mm/dd/yyyy'), ('dmy', 'dd/mm/yyyy'), ('ymd', 'yyyy-mm-dd'), ('mdy', 'mm-dd-yyyy'), ('dmy', 'dd-mm-yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('5', ''), ('4', ''), ('8', ''), ('6', ''), ('9', ''), ('2', ''), ('7', ''), ('3', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='contribution_status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('pending', 'pending'), ('verified', 'verified')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('All', 'All'), ('Hourly', 'Hourly'), ('Weekly', 'Weekly')], max_length=100, null=True),
        ),
    ]
