# Generated by Django 3.2.6 on 2022-05-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220516_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_import',
            name='Pending',
            field=models.CharField(blank=True, choices=[('Partial Success', 'Partial Success'), ('Success', 'Success'), ('Error', 'Error')], default='Success', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='data_import',
            name='import_type',
            field=models.CharField(blank=True, choices=[('Update Existing Records', 'Update Existing Records'), ('Insert New Records', 'Insert New Records')], default='Insert New Records', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('Table MultiSelect', ''), ('Tab Break', ''), ('Code', ''), ('Date', ''), ('Dynamic Link', ''), ('Read Only', ''), ('Select', ''), ('JSON', ''), ('HTML Editor', ''), ('Image', ''), ('Link', ''), ('Small Text', ''), ('Duration', ''), ('Fold', ''), ('Password', ''), ('Currency', ''), ('Attach Image', ''), ('Data', ''), ('Float', ''), ('Long Text', ''), ('Table', ''), ('Barcode', ''), ('Check', ''), ('Percent', ''), ('Color', ''), ('Markdown Editor', ''), ('Attach', ''), ('Rating', ''), ('Phone', ''), ('Heading', ''), ('Text', ''), ('Button', ''), ('Int', ''), ('Time', ''), ('Datetime', ''), ('Section Break', ''), ('Signature', ''), ('HTML', ''), ('Geolocation', ''), ('Text Editor', ''), ('Icon', ''), ('Autocomplete', ''), ('Column Break', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('7', ''), ('6', ''), ('3', ''), ('2', ''), ('5', ''), ('1', ''), ('8', ''), ('4', ''), ('9', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Document', 'Document'), ('System', 'System'), ('Other', 'Other'), ('Setup', 'Setup')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('10', 'Yellow'), ('3', 'Gray'), ('4', 'Green'), ('1', 'Blue'), ('9', 'Red'), ('8', 'Purple'), ('7', 'Pink'), ('2', 'Cyan'), ('5', 'Light Blue'), ('6', 'Orange')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('Document', 'Document'), ('System', 'System'), ('Other', 'Other'), ('Setup', 'Setup')], max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar_item',
            name='item_type',
            field=models.CharField(choices=[('Separator', 'Separator'), ('Route', 'Route'), ('Action', 'Action')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='license_type',
            field=models.CharField(choices=[('GNU Affero General', 'GNU Affero General'), ('Public License', 'Public License'), ('MIT License', 'MIT License'), ('GNU General Public License', 'GNU General Public License')], max_length=255),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Error', 'Error'), ('Queued', 'Queued'), ('Completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Query Report', 'Query Report'), ('Script Report', 'Script Report'), ('Report Builder', 'Report Builder'), ('Custom Report', 'Custom Report')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('Date', 'Date'), ('ManyToManyField', 'ManyToManyField'), ('Currency', 'Currency'), ('Float', 'Float'), ('IntigerField', 'IntigerField'), ('OneToOneRelation', 'OneToOneRelation'), ('ManyToOneRelation', 'ManyToOneRelation'), ('boolean', 'boolean'), ('OneToManyRelation', 'OneToManyRelation'), ('charfield', 'charfield'), ('ForeignKey', 'ForeignKey'), ('DateField', 'DateField')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_log',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Complete', 'Complete'), ('Failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Cron', 'Cron'), ('Yearly', 'Yearly'), ('Hourly', 'Hourly'), ('Daily Long', 'Daily Long'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Monthly Long', 'Monthly Long'), ('Hourly Long', 'Hourly Long'), ('Annual', 'Annual'), ('Weekly Long', 'Weekly Long'), ('All', 'All')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('After Insert', 'After Insert'), ('Before Validate', 'Before Validate'), ('On Payment Authorization', 'On Payment Authorization'), ('Before Save', 'Before Save'), ('Before Insert', 'Before Insert'), ('Before Delete', 'Before Delete'), ('Before Submit', 'Before Submit'), ('After Save', 'After Save'), ('Before Cancel', 'Before Cancel'), ('After Cancel', 'After Cancel'), ('After Submit', 'After Submit'), ('After Delete', 'After Delete'), ('Before Save', 'After Save')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Cron', 'Cron'), ('Yearly', 'Yearly'), ('Hourly', 'Hourly'), ('Daily Long', 'Daily Long'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Monthly Long', 'Monthly Long'), ('Hourly Long', 'Hourly Long'), ('Annual', 'Annual'), ('Weekly Long', 'Weekly Long'), ('All', 'All')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='script_type',
            field=models.CharField(choices=[('Scheduler Event', 'Scheduler Event'), ('Permission Query', 'Permission Query'), ('DocType Event', 'DocType Event'), ('API', 'API')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('7', ''), ('6', ''), ('3', ''), ('2', ''), ('5', ''), ('0', ''), ('8', ''), ('1', ''), ('4', ''), ('9', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('mdy', 'mm-dd-yyyy'), ('ymd', 'yyyy-mm-dd'), ('mdy', 'mm/dd/yyyy'), ('dmy', 'dd-mm-yyyy'), ('dmy', 'dd/mm/yyyy'), ('dmy', 'dd.mm.yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Thursday', 'Thursday'), ('Monday', 'Monday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('7', ''), ('6', ''), ('3', ''), ('2', ''), ('5', ''), ('8', ''), ('4', ''), ('9', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='time_format',
            field=models.CharField(choices=[('12', 'HH:mm'), ('24', 'HH:mm:ss')], max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='contribution_status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('verified', 'verified')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='desk_theme',
            field=models.CharField(blank=True, choices=[('Dark', 'Dark'), ('Automatic', 'Automatic'), ('Light', 'Light')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('All', 'All'), ('Hourly', 'Hourly'), ('Weekly', 'Weekly')], max_length=100, null=True),
        ),
    ]
