# Generated by Django 3.2.6 on 2022-05-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220516_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_import',
            name='Pending',
            field=models.CharField(blank=True, choices=[('Success', 'Success'), ('Partial Success', 'Partial Success'), ('Error', 'Error')], default='Success', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='data_import',
            name='import_type',
            field=models.CharField(blank=True, choices=[('Insert New Records', 'Insert New Records'), ('Update Existing Records', 'Update Existing Records')], default='Insert New Records', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('Dynamic Link', ''), ('Datetime', ''), ('Float', ''), ('Link', ''), ('Code', ''), ('HTML', ''), ('Int', ''), ('Table MultiSelect', ''), ('Percent', ''), ('Data', ''), ('Text Editor', ''), ('HTML Editor', ''), ('Read Only', ''), ('Long Text', ''), ('Attach Image', ''), ('Markdown Editor', ''), ('Barcode', ''), ('Column Break', ''), ('Geolocation', ''), ('Fold', ''), ('Heading', ''), ('Rating', ''), ('Small Text', ''), ('Image', ''), ('Date', ''), ('Button', ''), ('Duration', ''), ('Text', ''), ('Password', ''), ('Attach', ''), ('Phone', ''), ('Signature', ''), ('Select', ''), ('Table', ''), ('Autocomplete', ''), ('Color', ''), ('Section Break', ''), ('Tab Break', ''), ('Icon', ''), ('Currency', ''), ('Time', ''), ('Check', ''), ('JSON', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('1', ''), ('2', ''), ('3', ''), ('5', ''), ('6', ''), ('7', ''), ('9', ''), ('4', ''), ('8', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Document', 'Document'), ('Setup', 'Setup'), ('System', 'System')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='name_case',
            field=models.CharField(blank=True, choices=[('Title Case', 'Title Case'), ('UPPER CASE', 'UPPER CASE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('6', 'Orange'), ('2', 'Cyan'), ('7', 'Pink'), ('4', 'Green'), ('1', 'Blue'), ('5', 'Light Blue'), ('3', 'Gray'), ('8', 'Purple'), ('10', 'Yellow'), ('9', 'Red')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('Other', 'Other'), ('Document', 'Document'), ('Setup', 'Setup'), ('System', 'System')], max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar_item',
            name='item_type',
            field=models.CharField(choices=[('Separator', 'Separator'), ('Action', 'Action'), ('Route', 'Route')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='license_type',
            field=models.CharField(choices=[('GNU General Public License', 'GNU General Public License'), ('Public License', 'Public License'), ('GNU Affero General', 'GNU Affero General'), ('MIT License', 'MIT License')], max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='standard',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Queued', 'Queued'), ('Error', 'Error')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_standard',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Script Report', 'Script Report'), ('Report Builder', 'Report Builder'), ('Custom Report', 'Custom Report'), ('Query Report', 'Query Report')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('ForeignKey', 'ForeignKey'), ('OneToOneRelation', 'OneToOneRelation'), ('ManyToOneRelation', 'ManyToOneRelation'), ('Currency', 'Currency'), ('DateField', 'DateField'), ('boolean', 'boolean'), ('charfield', 'charfield'), ('OneToManyRelation', 'OneToManyRelation'), ('ManyToManyField', 'ManyToManyField'), ('IntigerField', 'IntigerField'), ('Date', 'Date'), ('Float', 'Float')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_log',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Failed', 'Failed'), ('Scheduled', 'Scheduled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('Annual', 'Annual'), ('Cron', 'Cron'), ('Hourly', 'Hourly'), ('Weekly', 'Weekly'), ('Hourly Long', 'Hourly Long'), ('Monthly', 'Monthly'), ('All', 'All'), ('Daily Long', 'Daily Long'), ('Daily', 'Daily'), ('Monthly Long', 'Monthly Long'), ('Weekly Long', 'Weekly Long')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('Before Insert', 'Before Insert'), ('After Insert', 'After Insert'), ('Before Delete', 'Before Delete'), ('Before Submit', 'Before Submit'), ('Before Validate', 'Before Validate'), ('After Submit', 'After Submit'), ('After Delete', 'After Delete'), ('Before Save', 'After Save'), ('On Payment Authorization', 'On Payment Authorization'), ('Before Cancel', 'Before Cancel'), ('Before Save', 'Before Save'), ('After Cancel', 'After Cancel'), ('After Save', 'After Save')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('Annual', 'Annual'), ('Cron', 'Cron'), ('Hourly', 'Hourly'), ('Weekly', 'Weekly'), ('Hourly Long', 'Hourly Long'), ('Monthly', 'Monthly'), ('All', 'All'), ('Daily Long', 'Daily Long'), ('Daily', 'Daily'), ('Monthly Long', 'Monthly Long'), ('Weekly Long', 'Weekly Long')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('0', ''), ('1', ''), ('2', ''), ('3', ''), ('5', ''), ('6', ''), ('7', ''), ('9', ''), ('4', ''), ('8', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('mdy', 'mm/dd/yyyy'), ('dmy', 'dd.mm.yyyy'), ('ymd', 'yyyy-mm-dd'), ('dmy', 'dd-mm-yyyy'), ('dmy', 'dd/mm/yyyy'), ('mdy', 'mm-dd-yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Monday', 'Monday'), ('Saturday', 'Saturday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('2', ''), ('3', ''), ('5', ''), ('6', ''), ('7', ''), ('9', ''), ('4', ''), ('8', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='time_format',
            field=models.CharField(choices=[('24', 'HH:mm:ss'), ('12', 'HH:mm')], max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='contribution_status',
            field=models.CharField(choices=[('verified', 'verified'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='desk_theme',
            field=models.CharField(blank=True, choices=[('Light', 'Light'), ('Automatic', 'Automatic'), ('Dark', 'Dark')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('All', 'All'), ('Weekly', 'Weekly')], max_length=100, null=True),
        ),
    ]
