# Generated by Django 3.2.6 on 2022-05-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220516_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_import',
            name='Pending',
            field=models.CharField(blank=True, choices=[('Error', 'Error'), ('Success', 'Success'), ('Partial Success', 'Partial Success')], default='Success', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='data_import',
            name='import_type',
            field=models.CharField(blank=True, choices=[('Update Existing Records', 'Update Existing Records'), ('Insert New Records', 'Insert New Records')], default='Insert New Records', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('Code', ''), ('Check', ''), ('Geolocation', ''), ('Float', ''), ('Table', ''), ('Text', ''), ('Long Text', ''), ('Icon', ''), ('Autocomplete', ''), ('Currency', ''), ('Date', ''), ('Data', ''), ('HTML Editor', ''), ('Table MultiSelect', ''), ('Fold', ''), ('HTML', ''), ('Dynamic Link', ''), ('Tab Break', ''), ('Select', ''), ('Duration', ''), ('Barcode', ''), ('Password', ''), ('Read Only', ''), ('Datetime', ''), ('Column Break', ''), ('Signature', ''), ('Attach Image', ''), ('Button', ''), ('Section Break', ''), ('Markdown Editor', ''), ('Phone', ''), ('Color', ''), ('Heading', ''), ('JSON', ''), ('Attach', ''), ('Time', ''), ('Image', ''), ('Small Text', ''), ('Text Editor', ''), ('Rating', ''), ('Int', ''), ('Percent', ''), ('Link', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('4', ''), ('6', ''), ('5', ''), ('8', ''), ('9', ''), ('3', ''), ('2', ''), ('7', ''), ('1', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Setup', 'Setup'), ('System', 'System'), ('Document', 'Document'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='name_case',
            field=models.CharField(blank=True, choices=[('UPPER CASE', 'UPPER CASE'), ('Title Case', 'Title Case')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('7', 'Pink'), ('1', 'Blue'), ('4', 'Green'), ('9', 'Red'), ('3', 'Gray'), ('5', 'Light Blue'), ('8', 'Purple'), ('10', 'Yellow'), ('2', 'Cyan'), ('6', 'Orange')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('Setup', 'Setup'), ('System', 'System'), ('Document', 'Document'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar_item',
            name='item_type',
            field=models.CharField(choices=[('Separator', 'Separator'), ('Route', 'Route'), ('Action', 'Action')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='license_type',
            field=models.CharField(choices=[('GNU Affero General', 'GNU Affero General'), ('MIT License', 'MIT License'), ('Public License', 'Public License'), ('GNU General Public License', 'GNU General Public License')], max_length=255),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Error', 'Error'), ('Queued', 'Queued'), ('Completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Custom Report', 'Custom Report'), ('Script Report', 'Script Report'), ('Report Builder', 'Report Builder'), ('Query Report', 'Query Report')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('charfield', 'charfield'), ('IntigerField', 'IntigerField'), ('OneToOneRelation', 'OneToOneRelation'), ('ManyToOneRelation', 'ManyToOneRelation'), ('Float', 'Float'), ('boolean', 'boolean'), ('ForeignKey', 'ForeignKey'), ('DateField', 'DateField'), ('OneToManyRelation', 'OneToManyRelation'), ('ManyToManyField', 'ManyToManyField'), ('Currency', 'Currency'), ('Date', 'Date')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_log',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Scheduled', 'Scheduled'), ('Failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('Hourly Long', 'Hourly Long'), ('Daily Long', 'Daily Long'), ('Weekly Long', 'Weekly Long'), ('Weekly', 'Weekly'), ('Annual', 'Annual'), ('Cron', 'Cron'), ('Monthly Long', 'Monthly Long'), ('Daily', 'Daily'), ('Hourly', 'Hourly'), ('Yearly', 'Yearly'), ('All', 'All'), ('Monthly', 'Monthly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('After Submit', 'After Submit'), ('Before Delete', 'Before Delete'), ('After Save', 'After Save'), ('Before Save', 'Before Save'), ('After Delete', 'After Delete'), ('On Payment Authorization', 'On Payment Authorization'), ('Before Submit', 'Before Submit'), ('Before Save', 'After Save'), ('Before Validate', 'Before Validate'), ('Before Insert', 'Before Insert'), ('After Insert', 'After Insert'), ('After Cancel', 'After Cancel'), ('Before Cancel', 'Before Cancel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('Hourly Long', 'Hourly Long'), ('Daily Long', 'Daily Long'), ('Weekly Long', 'Weekly Long'), ('Weekly', 'Weekly'), ('Annual', 'Annual'), ('Cron', 'Cron'), ('Monthly Long', 'Monthly Long'), ('Daily', 'Daily'), ('Hourly', 'Hourly'), ('Yearly', 'Yearly'), ('All', 'All'), ('Monthly', 'Monthly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='script_type',
            field=models.CharField(choices=[('API', 'API'), ('Permission Query', 'Permission Query'), ('Scheduler Event', 'Scheduler Event'), ('DocType Event', 'DocType Event')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('0', ''), ('4', ''), ('6', ''), ('5', ''), ('8', ''), ('9', ''), ('3', ''), ('2', ''), ('7', ''), ('1', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('mdy', 'mm/dd/yyyy'), ('ymd', 'yyyy-mm-dd'), ('dmy', 'dd/mm/yyyy'), ('dmy', 'dd.mm.yyyy'), ('dmy', 'dd-mm-yyyy'), ('mdy', 'mm-dd-yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('4', ''), ('6', ''), ('5', ''), ('8', ''), ('9', ''), ('3', ''), ('2', ''), ('7', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='time_format',
            field=models.CharField(choices=[('12', 'HH:mm'), ('24', 'HH:mm:ss')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='desk_theme',
            field=models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Light', 'Light'), ('Dark', 'Dark')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('All', 'All'), ('Weekly', 'Weekly'), ('Hourly', 'Hourly')], max_length=100, null=True),
        ),
    ]
