# Generated by Django 3.2.6 on 2022-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220516_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_import',
            name='import_type',
            field=models.CharField(blank=True, choices=[('Insert New Records', 'Insert New Records'), ('Update Existing Records', 'Update Existing Records')], default='Insert New Records', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('Date', ''), ('Attach Image', ''), ('Table MultiSelect', ''), ('Markdown Editor', ''), ('Percent', ''), ('Column Break', ''), ('Small Text', ''), ('Heading', ''), ('Float', ''), ('Text', ''), ('Data', ''), ('Tab Break', ''), ('Int', ''), ('Image', ''), ('Geolocation', ''), ('Rating', ''), ('Icon', ''), ('Check', ''), ('Table', ''), ('Long Text', ''), ('HTML', ''), ('Currency', ''), ('Autocomplete', ''), ('Button', ''), ('Fold', ''), ('Code', ''), ('Phone', ''), ('Duration', ''), ('Password', ''), ('Signature', ''), ('Dynamic Link', ''), ('Link', ''), ('JSON', ''), ('Read Only', ''), ('Attach', ''), ('Select', ''), ('Barcode', ''), ('Section Break', ''), ('Datetime', ''), ('Text Editor', ''), ('HTML Editor', ''), ('Time', ''), ('Color', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('9', ''), ('5', ''), ('8', ''), ('4', ''), ('3', ''), ('2', ''), ('6', ''), ('1', ''), ('7', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('System', 'System'), ('Setup', 'Setup'), ('Other', 'Other'), ('Document', 'Document')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='engine',
            field=models.CharField(blank=True, choices=[('InnoDB', 'InnoDB'), ('MyISAM', 'MyISAM')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='sort_order',
            field=models.CharField(blank=True, choices=[('ASC', 'ASC'), ('DESC', 'DESC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('8', 'Purple'), ('10', 'Yellow'), ('9', 'Red'), ('1', 'Blue'), ('3', 'Gray'), ('6', 'Orange'), ('7', 'Pink'), ('5', 'Light Blue'), ('4', 'Green'), ('2', 'Cyan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('System', 'System'), ('Setup', 'Setup'), ('Other', 'Other'), ('Document', 'Document')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='license_type',
            field=models.CharField(choices=[('GNU General Public License', 'GNU General Public License'), ('GNU Affero General', 'GNU Affero General'), ('MIT License', 'MIT License'), ('Public License', 'Public License')], max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='standard',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Error', 'Error'), ('Completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_standard',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Report Builder', 'Report Builder'), ('Query Report', 'Query Report'), ('Custom Report', 'Custom Report'), ('Script Report', 'Script Report')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('ForeignKey', 'ForeignKey'), ('ManyToOneRelation', 'ManyToOneRelation'), ('boolean', 'boolean'), ('ManyToManyField', 'ManyToManyField'), ('IntigerField', 'IntigerField'), ('DateField', 'DateField'), ('OneToOneRelation', 'OneToOneRelation'), ('Currency', 'Currency'), ('OneToManyRelation', 'OneToManyRelation'), ('Date', 'Date'), ('charfield', 'charfield'), ('Float', 'Float')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_log',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Failed', 'Failed'), ('Scheduled', 'Scheduled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly Long', 'Weekly Long'), ('Weekly', 'Weekly'), ('Hourly Long', 'Hourly Long'), ('Yearly', 'Yearly'), ('Daily Long', 'Daily Long'), ('Monthly', 'Monthly'), ('Cron', 'Cron'), ('Monthly Long', 'Monthly Long'), ('All', 'All'), ('Annual', 'Annual'), ('Hourly', 'Hourly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('On Payment Authorization', 'On Payment Authorization'), ('Before Validate', 'Before Validate'), ('Before Save', 'Before Save'), ('Before Insert', 'Before Insert'), ('After Insert', 'After Insert'), ('After Save', 'After Save'), ('Before Submit', 'Before Submit'), ('Before Delete', 'Before Delete'), ('Before Save', 'After Save'), ('Before Cancel', 'Before Cancel'), ('After Cancel', 'After Cancel'), ('After Submit', 'After Submit'), ('After Delete', 'After Delete')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly Long', 'Weekly Long'), ('Weekly', 'Weekly'), ('Hourly Long', 'Hourly Long'), ('Yearly', 'Yearly'), ('Daily Long', 'Daily Long'), ('Monthly', 'Monthly'), ('Cron', 'Cron'), ('Monthly Long', 'Monthly Long'), ('All', 'All'), ('Annual', 'Annual'), ('Hourly', 'Hourly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='script_type',
            field=models.CharField(choices=[('Permission Query', 'Permission Query'), ('Scheduler Event', 'Scheduler Event'), ('API', 'API'), ('DocType Event', 'DocType Event')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('0', ''), ('9', ''), ('8', ''), ('5', ''), ('4', ''), ('3', ''), ('2', ''), ('6', ''), ('1', ''), ('7', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('mdy', 'mm/dd/yyyy'), ('ymd', 'yyyy-mm-dd'), ('dmy', 'dd.mm.yyyy'), ('dmy', 'dd-mm-yyyy'), ('dmy', 'dd/mm/yyyy'), ('mdy', 'mm-dd-yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Sunday', 'Sunday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('9', ''), ('5', ''), ('8', ''), ('4', ''), ('3', ''), ('2', ''), ('6', ''), ('7', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='contribution_status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('verified', 'verified')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='desk_theme',
            field=models.CharField(blank=True, choices=[('Dark', 'Dark'), ('Light', 'Light'), ('Automatic', 'Automatic')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('All', 'All'), ('Hourly', 'Hourly')], max_length=100, null=True),
        ),
    ]
