# Generated by Django 3.2.6 on 2022-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220516_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_import',
            name='Pending',
            field=models.CharField(blank=True, choices=[('Partial Success', 'Partial Success'), ('Success', 'Success'), ('Error', 'Error')], default='Success', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='data_import',
            name='import_type',
            field=models.CharField(blank=True, choices=[('Update Existing Records', 'Update Existing Records'), ('Insert New Records', 'Insert New Records')], default='Insert New Records', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('Check', ''), ('Date', ''), ('Autocomplete', ''), ('Int', ''), ('Small Text', ''), ('Color', ''), ('Column Break', ''), ('Barcode', ''), ('Tab Break', ''), ('HTML', ''), ('Float', ''), ('Rating', ''), ('Section Break', ''), ('Table MultiSelect', ''), ('Geolocation', ''), ('Fold', ''), ('Percent', ''), ('Time', ''), ('Data', ''), ('Duration', ''), ('Markdown Editor', ''), ('Long Text', ''), ('Datetime', ''), ('Code', ''), ('Button', ''), ('Currency', ''), ('Text Editor', ''), ('Image', ''), ('Read Only', ''), ('Password', ''), ('JSON', ''), ('Icon', ''), ('Select', ''), ('HTML Editor', ''), ('Link', ''), ('Dynamic Link', ''), ('Attach Image', ''), ('Attach', ''), ('Phone', ''), ('Table', ''), ('Signature', ''), ('Heading', ''), ('Text', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('5', ''), ('1', ''), ('8', ''), ('4', ''), ('2', ''), ('6', ''), ('7', ''), ('3', ''), ('9', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Setup', 'Setup'), ('Document', 'Document'), ('Other', 'Other'), ('System', 'System')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='engine',
            field=models.CharField(blank=True, choices=[('MyISAM', 'MyISAM'), ('InnoDB', 'InnoDB')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='name_case',
            field=models.CharField(blank=True, choices=[('Title Case', 'Title Case'), ('UPPER CASE', 'UPPER CASE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='sort_order',
            field=models.CharField(blank=True, choices=[('DESC', 'DESC'), ('ASC', 'ASC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('5', 'Light Blue'), ('4', 'Green'), ('3', 'Gray'), ('10', 'Yellow'), ('9', 'Red'), ('1', 'Blue'), ('8', 'Purple'), ('2', 'Cyan'), ('7', 'Pink'), ('6', 'Orange')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('Setup', 'Setup'), ('System', 'System'), ('Document', 'Document'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar_item',
            name='item_type',
            field=models.CharField(choices=[('Route', 'Route'), ('Action', 'Action'), ('Separator', 'Separator')], max_length=100),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Queued', 'Queued'), ('Error', 'Error')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Script Report', 'Script Report'), ('Query Report', 'Query Report'), ('Custom Report', 'Custom Report'), ('Report Builder', 'Report Builder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('Currency', 'Currency'), ('IntigerField', 'IntigerField'), ('boolean', 'boolean'), ('ManyToOneRelation', 'ManyToOneRelation'), ('DateField', 'DateField'), ('ManyToManyField', 'ManyToManyField'), ('Float', 'Float'), ('charfield', 'charfield'), ('OneToManyRelation', 'OneToManyRelation'), ('OneToOneRelation', 'OneToOneRelation'), ('Date', 'Date'), ('ForeignKey', 'ForeignKey')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_log',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Complete', 'Complete'), ('Failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('Hourly Long', 'Hourly Long'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Annual', 'Annual'), ('Yearly', 'Yearly'), ('Hourly', 'Hourly'), ('Weekly Long', 'Weekly Long'), ('Monthly Long', 'Monthly Long'), ('Daily', 'Daily'), ('Cron', 'Cron'), ('Daily Long', 'Daily Long'), ('All', 'All')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('After Delete', 'After Delete'), ('Before Save', 'Before Save'), ('Before Insert', 'Before Insert'), ('Before Submit', 'Before Submit'), ('After Cancel', 'After Cancel'), ('After Submit', 'After Submit'), ('Before Save', 'After Save'), ('After Save', 'After Save'), ('Before Validate', 'Before Validate'), ('Before Delete', 'Before Delete'), ('After Insert', 'After Insert'), ('On Payment Authorization', 'On Payment Authorization'), ('Before Cancel', 'Before Cancel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('Hourly Long', 'Hourly Long'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Annual', 'Annual'), ('Yearly', 'Yearly'), ('Hourly', 'Hourly'), ('Weekly Long', 'Weekly Long'), ('Monthly Long', 'Monthly Long'), ('Daily', 'Daily'), ('Cron', 'Cron'), ('Daily Long', 'Daily Long'), ('All', 'All')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='script_type',
            field=models.CharField(choices=[('API', 'API'), ('Permission Query', 'Permission Query'), ('DocType Event', 'DocType Event'), ('Scheduler Event', 'Scheduler Event')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('5', ''), ('1', ''), ('8', ''), ('4', ''), ('2', ''), ('6', ''), ('7', ''), ('3', ''), ('0', ''), ('9', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('mdy', 'mm-dd-yyyy'), ('dmy', 'dd.mm.yyyy'), ('mdy', 'mm/dd/yyyy'), ('ymd', 'yyyy-mm-dd'), ('dmy', 'dd-mm-yyyy'), ('dmy', 'dd/mm/yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('5', ''), ('8', ''), ('4', ''), ('2', ''), ('6', ''), ('7', ''), ('3', ''), ('9', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='contribution_status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('pending', 'pending'), ('verified', 'verified')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='desk_theme',
            field=models.CharField(blank=True, choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Automatic', 'Automatic')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Hourly', 'Hourly'), ('All', 'All')], max_length=100, null=True),
        ),
    ]
