# Generated by Django 3.2.6 on 2022-05-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220516_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_import',
            name='Pending',
            field=models.CharField(blank=True, choices=[('Error', 'Error'), ('Success', 'Success'), ('Partial Success', 'Partial Success')], default='Success', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('Code', ''), ('Table MultiSelect', ''), ('Data', ''), ('Check', ''), ('Section Break', ''), ('Dynamic Link', ''), ('Read Only', ''), ('Button', ''), ('Percent', ''), ('Small Text', ''), ('Long Text', ''), ('Select', ''), ('Link', ''), ('Time', ''), ('Rating', ''), ('Color', ''), ('Date', ''), ('Image', ''), ('Int', ''), ('Attach', ''), ('Duration', ''), ('JSON', ''), ('Barcode', ''), ('Phone', ''), ('Signature', ''), ('Column Break', ''), ('Heading', ''), ('Text Editor', ''), ('Text', ''), ('Tab Break', ''), ('Password', ''), ('Table', ''), ('Attach Image', ''), ('Markdown Editor', ''), ('Fold', ''), ('Geolocation', ''), ('HTML Editor', ''), ('Datetime', ''), ('HTML', ''), ('Currency', ''), ('Autocomplete', ''), ('Icon', ''), ('Float', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('1', ''), ('6', ''), ('5', ''), ('9', ''), ('8', ''), ('3', ''), ('2', ''), ('7', ''), ('4', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Document', 'Document'), ('System', 'System'), ('Setup', 'Setup'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='name_case',
            field=models.CharField(blank=True, choices=[('UPPER CASE', 'UPPER CASE'), ('Title Case', 'Title Case')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('2', 'Cyan'), ('7', 'Pink'), ('10', 'Yellow'), ('6', 'Orange'), ('3', 'Gray'), ('1', 'Blue'), ('8', 'Purple'), ('4', 'Green'), ('5', 'Light Blue'), ('9', 'Red')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('Document', 'Document'), ('System', 'System'), ('Setup', 'Setup'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar_item',
            name='item_type',
            field=models.CharField(choices=[('Route', 'Route'), ('Separator', 'Separator'), ('Action', 'Action')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='license_type',
            field=models.CharField(choices=[('GNU Affero General', 'GNU Affero General'), ('MIT License', 'MIT License'), ('GNU General Public License', 'GNU General Public License'), ('Public License', 'Public License')], max_length=255),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Error', 'Error'), ('Queued', 'Queued'), ('Completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Report Builder', 'Report Builder'), ('Script Report', 'Script Report'), ('Query Report', 'Query Report'), ('Custom Report', 'Custom Report')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('boolean', 'boolean'), ('ManyToManyField', 'ManyToManyField'), ('charfield', 'charfield'), ('DateField', 'DateField'), ('ManyToOneRelation', 'ManyToOneRelation'), ('Currency', 'Currency'), ('ForeignKey', 'ForeignKey'), ('OneToOneRelation', 'OneToOneRelation'), ('Float', 'Float'), ('Date', 'Date'), ('OneToManyRelation', 'OneToManyRelation'), ('IntigerField', 'IntigerField')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('Cron', 'Cron'), ('Daily', 'Daily'), ('Daily Long', 'Daily Long'), ('All', 'All'), ('Monthly Long', 'Monthly Long'), ('Monthly', 'Monthly'), ('Hourly', 'Hourly'), ('Hourly Long', 'Hourly Long'), ('Annual', 'Annual'), ('Yearly', 'Yearly'), ('Weekly Long', 'Weekly Long'), ('Weekly', 'Weekly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('Before Save', 'After Save'), ('Before Insert', 'Before Insert'), ('After Delete', 'After Delete'), ('Before Save', 'Before Save'), ('After Submit', 'After Submit'), ('After Save', 'After Save'), ('Before Cancel', 'Before Cancel'), ('Before Validate', 'Before Validate'), ('After Cancel', 'After Cancel'), ('Before Submit', 'Before Submit'), ('After Insert', 'After Insert'), ('On Payment Authorization', 'On Payment Authorization'), ('Before Delete', 'Before Delete')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('Cron', 'Cron'), ('Daily', 'Daily'), ('Daily Long', 'Daily Long'), ('All', 'All'), ('Monthly Long', 'Monthly Long'), ('Monthly', 'Monthly'), ('Hourly', 'Hourly'), ('Hourly Long', 'Hourly Long'), ('Annual', 'Annual'), ('Yearly', 'Yearly'), ('Weekly Long', 'Weekly Long'), ('Weekly', 'Weekly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='script_type',
            field=models.CharField(choices=[('Scheduler Event', 'Scheduler Event'), ('DocType Event', 'DocType Event'), ('Permission Query', 'Permission Query'), ('API', 'API')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('0', ''), ('1', ''), ('6', ''), ('5', ''), ('9', ''), ('8', ''), ('3', ''), ('2', ''), ('7', ''), ('4', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('dmy', 'dd/mm/yyyy'), ('mdy', 'mm/dd/yyyy'), ('dmy', 'dd-mm-yyyy'), ('mdy', 'mm-dd-yyyy'), ('ymd', 'yyyy-mm-dd'), ('dmy', 'dd.mm.yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('6', ''), ('5', ''), ('9', ''), ('8', ''), ('3', ''), ('2', ''), ('7', ''), ('4', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='contribution_status',
            field=models.CharField(choices=[('verified', 'verified'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='desk_theme',
            field=models.CharField(blank=True, choices=[('Dark', 'Dark'), ('Automatic', 'Automatic'), ('Light', 'Light')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=100, null=True),
        ),
    ]
