# Generated by Django 3.2.6 on 2022-05-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220516_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_import',
            name='Pending',
            field=models.CharField(blank=True, choices=[('Success', 'Success'), ('Partial Success', 'Partial Success'), ('Error', 'Error')], default='Success', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='data_import',
            name='import_type',
            field=models.CharField(blank=True, choices=[('Insert New Records', 'Insert New Records'), ('Update Existing Records', 'Update Existing Records')], default='Insert New Records', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='fieldtype',
            field=models.CharField(blank=True, choices=[('Attach Image', ''), ('Table MultiSelect', ''), ('Float', ''), ('Barcode', ''), ('Markdown Editor', ''), ('Phone', ''), ('Date', ''), ('Datetime', ''), ('Time', ''), ('Image', ''), ('Button', ''), ('Rating', ''), ('Long Text', ''), ('Link', ''), ('Color', ''), ('Currency', ''), ('Icon', ''), ('Read Only', ''), ('Section Break', ''), ('Table', ''), ('HTML', ''), ('Password', ''), ('Code', ''), ('Autocomplete', ''), ('Text', ''), ('Column Break', ''), ('Heading', ''), ('Check', ''), ('Tab Break', ''), ('Geolocation', ''), ('HTML Editor', ''), ('Select', ''), ('Percent', ''), ('Fold', ''), ('JSON', ''), ('Small Text', ''), ('Dynamic Link', ''), ('Attach', ''), ('Text Editor', ''), ('Signature', ''), ('Int', ''), ('Duration', ''), ('Data', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='precision',
            field=models.CharField(blank=True, choices=[('6', ''), ('9', ''), ('5', ''), ('7', ''), ('1', ''), ('2', ''), ('8', ''), ('4', ''), ('3', '')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='document_type',
            field=models.CharField(blank=True, choices=[('System', 'System'), ('Setup', 'Setup'), ('Document', 'Document'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctype_state',
            name='color',
            field=models.CharField(choices=[('5', 'Light Blue'), ('9', 'Red'), ('6', 'Orange'), ('7', 'Pink'), ('2', 'Cyan'), ('10', 'Yellow'), ('4', 'Green'), ('8', 'Purple'), ('3', 'Gray'), ('1', 'Blue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reference_doctype',
            field=models.CharField(choices=[('System', 'System'), ('Document', 'Document'), ('Other', 'Other'), ('Setup', 'Setup')], max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='license_type',
            field=models.CharField(choices=[('Public License', 'Public License'), ('MIT License', 'MIT License'), ('GNU Affero General', 'GNU Affero General'), ('GNU General Public License', 'GNU General Public License')], max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='standard',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prepared_report',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Error', 'Error'), ('Queued', 'Queued')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_standard',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Report Builder', 'Report Builder'), ('Query Report', 'Query Report'), ('Custom Report', 'Custom Report'), ('Script Report', 'Script Report')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_column',
            name='fieldtype',
            field=models.CharField(choices=[('OneToManyRelation', 'OneToManyRelation'), ('Currency', 'Currency'), ('ManyToOneRelation', 'ManyToOneRelation'), ('charfield', 'charfield'), ('ManyToManyField', 'ManyToManyField'), ('boolean', 'boolean'), ('DateField', 'DateField'), ('ForeignKey', 'ForeignKey'), ('Float', 'Float'), ('Date', 'Date'), ('OneToOneRelation', 'OneToOneRelation'), ('IntigerField', 'IntigerField')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduled_job_type',
            name='frequency',
            field=models.CharField(choices=[('Cron', 'Cron'), ('Weekly Long', 'Weekly Long'), ('Monthly Long', 'Monthly Long'), ('Daily Long', 'Daily Long'), ('Yearly', 'Yearly'), ('Daily', 'Daily'), ('Hourly', 'Hourly'), ('Hourly Long', 'Hourly Long'), ('All', 'All'), ('Weekly', 'Weekly'), ('Annual', 'Annual'), ('Monthly', 'Monthly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='doctype_event',
            field=models.CharField(choices=[('Before Insert', 'Before Insert'), ('Before Delete', 'Before Delete'), ('Before Save', 'Before Save'), ('After Delete', 'After Delete'), ('Before Save', 'After Save'), ('After Cancel', 'After Cancel'), ('On Payment Authorization', 'On Payment Authorization'), ('After Insert', 'After Insert'), ('After Submit', 'After Submit'), ('Before Submit', 'Before Submit'), ('After Save', 'After Save'), ('Before Cancel', 'Before Cancel'), ('Before Validate', 'Before Validate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='event_frequency',
            field=models.CharField(choices=[('Cron', 'Cron'), ('Weekly Long', 'Weekly Long'), ('Monthly Long', 'Monthly Long'), ('Daily Long', 'Daily Long'), ('Yearly', 'Yearly'), ('Daily', 'Daily'), ('Hourly', 'Hourly'), ('Hourly Long', 'Hourly Long'), ('All', 'All'), ('Weekly', 'Weekly'), ('Annual', 'Annual'), ('Monthly', 'Monthly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='server_script',
            name='script_type',
            field=models.CharField(choices=[('DocType Event', 'DocType Event'), ('API', 'API'), ('Scheduler Event', 'Scheduler Event'), ('Permission Query', 'Permission Query')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='currency_precision',
            field=models.CharField(choices=[('6', ''), ('9', ''), ('5', ''), ('7', ''), ('1', ''), ('2', ''), ('8', ''), ('4', ''), ('3', ''), ('0', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='date_format',
            field=models.CharField(choices=[('mdy', 'mm/dd/yyyy'), ('dmy', 'dd/mm/yyyy'), ('dmy', 'dd.mm.yyyy'), ('ymd', 'yyyy-mm-dd'), ('mdy', 'mm-dd-yyyy'), ('dmy', 'dd-mm-yyyy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='first_day_of_the_week',
            field=models.CharField(choices=[('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Tuesday', 'Tuesday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='float_precision',
            field=models.CharField(choices=[('6', ''), ('9', ''), ('5', ''), ('7', ''), ('2', ''), ('8', ''), ('4', ''), ('3', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='contribution_status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('verified', 'verified'), ('pending', 'pending')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='desk_theme',
            field=models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Light', 'Light'), ('Dark', 'Dark')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Hourly', 'Hourly'), ('Daily', 'Daily'), ('All', 'All')], max_length=100, null=True),
        ),
    ]
