from django.contrib import admin

from apps.core.models import Access_Log, Activity_Log, Block_Module, Comment, Communication_Link, Communication, Communication_Docperm, Data_Export, Data_Import_Log, Data_Import, DefaultValue, Deleted_Document, Docfield, Docshare, Doctype_Action, Doctype_State, Doctype, Domain_Settings, Domain, Dynamic_Link, Error_Log, Error_Snapshot, Feedback, File
      



admin.site.register(Access_Log)
admin.site.register(Activity_Log)
admin.site.register(Block_Module)
admin.site.register(Comment)
admin.site.register(Communication_Link)
admin.site.register(Communication)
admin.site.register(Communication_Docperm)
admin.site.register(Data_Export)
admin.site.register(Data_Import_Log)
admin.site.register(Data_Import)
admin.site.register(DefaultValue)
admin.site.register(Deleted_Document)
admin.site.register(Docfield)
admin.site.register(Docshare)
admin.site.register(Doctype_Action)
admin.site.register(Doctype_State)
admin.site.register(Doctype)
admin.site.register(Domain_Settings)
admin.site.register(Domain)
admin.site.register(Dynamic_Link)
admin.site.register(Error_Log)
admin.site.register(Error_Snapshot)
admin.site.register(Feedback)
admin.site.register(File)
# admin.site.register(Has_Domain)
# admin.site.register(Has_Role)
# admin.site.register(Install_Application)
# admin.site.register(Language)
# admin.site.register(Log_Setting_User)
# admin.site.register(Log_Settings)
# admin.site.register(Module_Def)
# admin.site.register(Module_Profile)
# admin.site.register(Navbar_Item)
# admin.site.register(Navbar_Settings)
# admin.site.register(Package)
# admin.site.register(Page)
# admin.site.register(Payment_Gateway)
# admin.site.register(Prepared_Report)
# admin.site.register(Report_Column)
# admin.site.register(Report_Filter)
# admin.site.register(Report)
# admin.site.register(Role_Profile)
# admin.site.register(Role)
# admin.site.register(Scheduled_Job_Log)
# admin.site.register(Scheduled_Job_Type)
# admin.site.register(Server_Script)
# admin.site.register(Session_Default)
# admin.site.register(Sms_Parameter)
# admin.site.register(Sms_Settings)
# admin.site.register(Success_Action)
# admin.site.register(System_Settings)
# admin.site.register(Test)
# admin.site.register(Transaction_Log)
# admin.site.register(Translation)
# admin.site.register(UserDocument_Type)
# admin.site.register(UserEmail)
# admin.site.register(UserGroup_Member)
# admin.site.register(UserGroup)
# admin.site.register(UserSelect_Document_Type)
# admin.site.register(UserSocial_Login)
# admin.site.register(UserType_Module)
# admin.site.register(UserType)
# admin.site.register(User)


