# Generated by Django 3.2.6 on 2022-05-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organization')),
                ('team_name', models.CharField(max_length=50)),
                ('team_no', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('organizations.organization',),
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
