# Generated by Django 3.2.6 on 2022-05-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20220516_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='dep',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organizations.department'),
        ),
    ]
